show databases;
use scott;
show tables;
use mysql;
DROP DATABASE scott;
Create Database scott;

SELECT * FROM emp;
-- NESTED QUERY ON SCOTT DATABASE

-- Q1
SELECT ENAME FROM emp WHERE SAL>(SELECT SAL FROM emp WHERE ENAME = 'FORD');
-- Q2
SELECT * FROM emp WHERE HIREDATE<(SELECT HIREDATE FROM emp WHERE ENAME = 'SCOTT' );
-- Q3
SELECT *, (SELECT MIN(SAL) FROM emp WHERE DEPTNO = DEPT.DEPTNO) AS MIN_SAL, (SELECT MAX(SAL) FROM emp WHERE DEPTNO = DEPT.DEPTNO) AS MAX_SAL FROM DEPT;
-- Q4
SELECT * FROM DEPT AS D WHERE DEPTNO IN (SELECT DEPTNO FROM emp E WHERE D.DEPTNO = E.DEPTNO);
-- Q5
SELECT * FROM emp WHERE empno NOT IN (SELECT DISTINCT MGR FROM emp WHERE MGR IS NOT NULL);
-- Q6
SELECT * FROM emp WHERE DEPTNO IN (SELECT DEPTNO FROM emp WHERE ENAME = 'JAMES');
-- Q7
SELECT * FROM emp WHERE SAL<=(SELECT SAL FROM emp WHERE ENAME = 'ADAMS');
-- Q8
SELECT * FROM emp WHERE MGR = (SELECT EMPNO FROM emp WHERE ENAME = 'BLAKE');
-- Q9
SELECT * FROM emp WHERE DEPTNO = (SELECT DEPTNO FROM emp WHERE ENAME = 'KING');
-- Q10
SELECT * FROM emp WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');
-- Q11
SELECT * FROM emp WHERE SAL<700 OR SAL>9999;

-- JOINS QUERY ON SCOTT DATABASE

-- Q1
SELECT E.* FROM emp AS E JOIN emp AS S ON E.HIREDATE < S.HIREDATE WHERE S.ENAME = 'SCOTT';
-- Q2
SELECT DEPT.DEPTNO,DNAME,LOC FROM DEPT JOIN emp ON DEPT.DEPTNO = EMP.DEPTNO GROUP BY DEPTNO,DNAME,LOC HAVING COUNT(*) = 3;
-- Q3
SELECT *, (SELECT min(sal) from emp where deptno=dept.deptno) as min_sal,(SELECT max(sal) from emp where deptno=dept.deptno) as max_sal from dept;
-- Q4
SELECT DNAME,B.DEPTNO, ENAME,SAL FROM emp A LEFT OUTER JOIN DEPT B ON A.DEPTNO = B.DEPTNO;
-- Q5
SELECT DNAME,B.DEPTNO, ENAME,SAL FROM emp a RIGHT OUTER JOIN DEPT B ON A.DEPTNO = B.DEPTNO;
-- Q6
SELECT DNAME,B.DEPTNO, ENAME,SAL FROM emp a RIGHT OUTER JOIN DEPT B ON A.DEPTNO = B.DEPTNO;
-- Q7
SELECT * FROM emp, DEPT;
-- Q8
SELECT D.DNAME FROM DEPT D WHERE NOT EXISTS (SELECT * FROM EMP E WHERE D.DEPTNO = E.DEPTNO);
-- Q9
SELECT DEPTNO, COUNT(*) FROM emp GROUP BY DEPTNO HAVING COUNT(*)>=1;
-- Q10
SELECT ENAME FROM emp a WHERE NOT EXISTS (SELECT 1 FROM emp B WHERE B.MGR = A.EMPNO);
-- Q11
SELECT * FROM emp WHERE DEPTNO IN (SELECT DEPTNO FROM emp WHERE ENAME = 'JAMES');
-- Q12
SELECT * FROM emp WHERE SAL<=(SELECT SAL FROM emp WHERE ENAME ='ADAMS');
-- Q13
SELECT EMPNO, ENAME, B.DEPTNO, DNAME, GRADE FROM emp A, DEPT B, SALGRADE C WHERE A.DEPTNO = B.DEPTNO AND SAL BETWEEN LOSAL AND HISAL;
-- Q14 
SELECT emp.ENAME, emp.JOB, emp.DEPTNO FROM emp WHERE DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');