-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 18:55:39 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Schema hospital
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospital` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `hospital` ;

-- -----------------------------------------------------
-- Table `hospital`.`procedure`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`procedure` (
  `code` INT NOT NULL,
  `name` TEXT NULL,
  `cost` REAL NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`physician`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`physician` (
  `employeeid` INT NOT NULL,
  `name` TEXT NULL,
  `position` TEXT NULL,
  `ssn` INT NULL,
  PRIMARY KEY (`employeeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`trained_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`trained_in` (
  `physician` INT NOT NULL,
  `treatment` INT NOT NULL,
  `certificationdate` DATE NULL,
  `certificationexpires` DATE NULL,
  PRIMARY KEY (`physician`, `treatment`),
  INDEX `FK_treatment_idx` (`treatment` ASC) VISIBLE,
  CONSTRAINT `FK_physician`
    FOREIGN KEY (`physician`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_treatment`
    FOREIGN KEY (`treatment`)
    REFERENCES `hospital`.`procedure` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`block`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`block` (
  `blockfloor` INT NOT NULL,
  `blockcode` INT NOT NULL,
  PRIMARY KEY (`blockfloor`, `blockcode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`room` (
  `roomnumber` INT NOT NULL,
  `roomtype` TEXT NULL,
  `blockfloor` INT NULL,
  `blockcode` INT NULL,
  `unavailable` TINYINT NULL,
  `block_blockfloor` INT NOT NULL,
  `block_blockcode` INT NOT NULL,
  PRIMARY KEY (`roomnumber`),
  INDEX `fk_room_block1_idx` (`block_blockfloor` ASC, `block_blockcode` ASC) VISIBLE,
  CONSTRAINT `fk_room_block1`
    FOREIGN KEY (`block_blockfloor` , `block_blockcode`)
    REFERENCES `hospital`.`block` (`blockfloor` , `blockcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`patient` (
  `ssn` INT NOT NULL,
  `name` TEXT NULL,
  `address` TEXT NULL,
  `phone` TEXT NULL,
  `insuranceid` INT NULL,
  `pcp` INT NULL,
  `physician_employeeid` INT NOT NULL,
  `physician_trained_in_physician` INT UNSIGNED NOT NULL,
  `physician_trained_in_treatment` INT NOT NULL,
  PRIMARY KEY (`ssn`),
  INDEX `fk_patient_physician1_idx` (`physician_employeeid` ASC, `physician_trained_in_physician` ASC, `physician_trained_in_treatment` ASC) VISIBLE,
  CONSTRAINT `fk_patient_physician1`
    FOREIGN KEY (`physician_employeeid`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`stay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`stay` (
  `stayid` INT NOT NULL,
  `patient` INT NULL,
  `room` INT NULL,
  `start_time` VARCHAR(45) NULL,
  `end_time` VARCHAR(45) NULL,
  PRIMARY KEY (`stayid`),
  INDEX `FK_stay_patient_idx` (`patient` ASC) VISIBLE,
  INDEX `FK_stay_room_idx` (`room` ASC) VISIBLE,
  CONSTRAINT `FK_stay_patient`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_stay_room`
    FOREIGN KEY (`room`)
    REFERENCES `hospital`.`room` (`roomnumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`nurse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`nurse` (
  `employeeid` INT NOT NULL,
  `name` TEXT NULL,
  `position` TEXT NULL,
  `registered` TINYINT NULL,
  `ssn` INT NULL,
  PRIMARY KEY (`employeeid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`department` (
  `departmentid` INT NOT NULL,
  `name` TEXT NULL,
  `head` INT NULL,
  `physician_employeeid` INT NOT NULL,
  `physician_trained_in_physician` INT UNSIGNED NOT NULL,
  `physician_trained_in_treatment` INT NOT NULL,
  PRIMARY KEY (`departmentid`),
  INDEX `fk_department_physician1_idx` (`physician_employeeid` ASC, `physician_trained_in_physician` ASC, `physician_trained_in_treatment` ASC) VISIBLE,
  CONSTRAINT `fk_department_physician1`
    FOREIGN KEY (`physician_employeeid`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`affiliated_with`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`affiliated_with` (
  `physician` INT NOT NULL,
  `department` INT NOT NULL,
  `primaryaffiliation` TINYINT NULL,
  PRIMARY KEY (`physician`, `department`),
  INDEX `fk_department_idx` (`department` ASC) VISIBLE,
  CONSTRAINT `fk_affiliated_with_physician`
    FOREIGN KEY (`physician`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_department`
    FOREIGN KEY (`department`)
    REFERENCES `hospital`.`department` (`departmentid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`medication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`medication` (
  `code` INT NOT NULL,
  `name` TEXT NULL,
  `brand` TEXT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`prescribes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`prescribes` (
  `physician` INT NOT NULL,
  `patient` INT NOT NULL,
  `medication` INT NOT NULL,
  `date` TIME NOT NULL,
  `appointment` INT NULL,
  `dose` TEXT NULL,
  PRIMARY KEY (`physician`, `patient`, `medication`, `date`),
  INDEX `fk_prescribes_patient1_idx` (`patient` ASC) VISIBLE,
  INDEX `fk_prescribes_medication_idx` (`medication` ASC) VISIBLE,
  CONSTRAINT `fk_prescribes_patient`
    FOREIGN KEY (`patient`)
    REFERENCES `hospital`.`patient` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescribes_physician`
    FOREIGN KEY (`physician`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescribes_medication`
    FOREIGN KEY (`medication`)
    REFERENCES `hospital`.`medication` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`appointment` (
  `appointmentid` INT NOT NULL,
  `patient` INT NULL,
  `prepnurse` INT NULL,
  `physician` INT NULL,
  `start_dt_time` TIME NULL,
  `end_dt_time` TIME NULL,
  `examinationroom` TEXT NULL,
  `nurse_employeeid` INT NULL,
  PRIMARY KEY (`appointmentid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`undergoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`undergoes` (
  `patient` INT NOT NULL,
  `procedure` INT NOT NULL,
  `stay` INT NOT NULL,
  `date` TIME NOT NULL,
  `physician` INT NULL,
  `assistingnurse` INT NULL,
  `stay_stayid` INT NOT NULL,
  `physician_employeeid` INT NOT NULL,
  `physician_trained_in_physician` INT UNSIGNED NOT NULL,
  `physician_trained_in_treatment` INT NOT NULL,
  `procedure_code` INT NOT NULL,
  `patient_ssn` INT NOT NULL,
  `nurse_employeeid` INT NOT NULL,
  PRIMARY KEY (`patient`, `procedure`, `stay`, `date`, `stay_stayid`),
  INDEX `fk_undergoes_stay1_idx` (`stay_stayid` ASC) VISIBLE,
  INDEX `fk_undergoes_physician1_idx` (`physician_employeeid` ASC, `physician_trained_in_physician` ASC, `physician_trained_in_treatment` ASC) VISIBLE,
  INDEX `fk_undergoes_procedure1_idx` (`procedure_code` ASC) VISIBLE,
  INDEX `fk_undergoes_patient1_idx` (`patient_ssn` ASC) VISIBLE,
  INDEX `fk_undergoes_nurse1_idx` (`nurse_employeeid` ASC) VISIBLE,
  CONSTRAINT `fk_undergoes_stay1`
    FOREIGN KEY (`stay_stayid`)
    REFERENCES `hospital`.`stay` (`stayid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_undergoes_physician1`
    FOREIGN KEY (`physician_employeeid`)
    REFERENCES `hospital`.`physician` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_undergoes_procedure1`
    FOREIGN KEY (`procedure_code`)
    REFERENCES `hospital`.`procedure` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_undergoes_patient1`
    FOREIGN KEY (`patient_ssn`)
    REFERENCES `hospital`.`patient` (`ssn`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_undergoes_nurse1`
    FOREIGN KEY (`nurse_employeeid`)
    REFERENCES `hospital`.`nurse` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospital`.`on_call`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospital`.`on_call` (
  `nurse` INT NOT NULL,
  `blockfloor` INT NOT NULL,
  `blockcode` INT NOT NULL,
  `oncallstart` TIME NOT NULL,
  `oncallend` TIME NOT NULL,
  PRIMARY KEY (`nurse`, `blockfloor`, `blockcode`, `oncallstart`, `oncallend`),
  INDEX `FK_block_idx` (`blockfloor` ASC, `blockcode` ASC) VISIBLE,
  CONSTRAINT `FK_on_call_nurse`
    FOREIGN KEY (`nurse`)
    REFERENCES `hospital`.`nurse` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_block`
    FOREIGN KEY (`blockfloor` , `blockcode`)
    REFERENCES `hospital`.`block` (`blockfloor` , `blockcode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
